// Generated automatically by cmake from version.h.in.

#ifndef TLDR_CLIENT_CMAKE_TEMPLATE_INCLUDE_VERSION_H_
#define TLDR_CLIENT_CMAKE_TEMPLATE_INCLUDE_VERSION_H_

#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 2
#define PROJECT_VERSION_PATCH 0

#endif  // TLDR_CLIENT_CMAKE_TEMPLATE_INCLUDE_VERSION_H_
